### PR TITLE
Fix builds 21

### LINKED ISSUE #21: Fix builds!
Need to update snapshot dependencies to the latest 1.3.0-SNAPSHOT and fix complication errors.

### PR DESCRIPTION
**Pull request by luan-cestari**
Fixes #21

### CODE REVIEW

File: src/test/java/com/redhat/lightblue/hook/audit/AbstractMongoTest.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+import org.junit.After;
+import org.junit.Assert;
+import org.junit.Before;
+import org.junit.BeforeClass;
+
+
+/**
+ * Created by lcestari on 1/9/15.
+ */
+public abstract class AbstractMongoTest extends AbstractJsonSchemaTest {
```
Comment (jewzaam) [inline src/test/java/com/redhat/lightblue/hook/audit/AbstractMongoTest.java]: I don't think adding this class is the right solution but will let it go until we remove these abstract mongo tests and move to the in memory mongo resource.
